/* eslint-disable @next/next/no-document-import-in-page */
import React, { ReactElement } from 'react';
import Document, {
  Html,
  Head,
  Main,
  NextScript,
  DocumentInitialProps,
  DocumentContext,
} from 'next/document';

export default class MyDocument extends Document {
  static async getInitialProps(
    ctx: DocumentContext
  ): Promise<DocumentInitialProps> {
    const initialProps = await Document.getInitialProps(ctx);
    return initialProps;
  }

  render(): ReactElement {
    return (
      <Html lang='en' className='dark'>
        <Head>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <link
            href='https://fonts.googleapis.com/css?family=Poppins:100,200,300,regular,500,600,700,800&display=swap'
            rel='stylesheet'
          />
        </Head>
        <body className='font-sans body-color'>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
